### ISSUE TITLE
How set preventDefault to onEmojiClick

### ISSUE THREAD

**Issue by KirillYoYo** [ealush/emoji-picker#38]
How can i set event.preventDefault to onEmojiClick callback?

**Comment by KirillYoYo** [comment]
ok, its can solve like:
`componentDidMount() {
    const el = document.getElementsByClassName('emoji-list')[0];
    el.addEventListener(
      'click', this.stopDefAction, false
    );
  }`

**Comment by ealush** [comment]
Hey @KirillYoYo, thanks for reaching out 👍 
I just pushed a new version to the picker which supports you in two ways.

1. preventDefault is being applied to all emoji click events.
2. onEmojiClick now also passes back the event as well

Now, when clicking an emojy, onEmojiClick accepts: `emojiName, emojiData, event`.

so: `onEmojiClick(name, data, e) { ... };`

I know `event` is traditionally positioned in the beginning, but since it breaks backwards compatibility, I will only move it there in the next major version.

Hope this helps

**Comment by ealush** [comment]
No more comments. Closing :)
